language: php

notifications:
  email:
    on_success: never
    on_failure: never

php:
  - 5.6
  - 7.1

env:
  - WP_VERSION=latest WC_VERSION=3.2.6 WP_MULTISITE=0
  - WP_VERSION=latest WC_VERSION=3.4.2 WP_MULTISITE=1

before_script:
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION $WC_VERSION

script: phpunit